#!/bin/bash
# Mon script de post installation desktop Debian 6.0
#
# Nicolargo - 06/2011
# GPL
#
# Syntaxe: # su - -c "./siddesktoppostinstall.sh"
# Syntaxe: or # sudo ./siddesktoppostinstall.sh
VERSION="1.2"

#=============================================================================
# Liste des applications à installer
# A adapter à vos besoins...
#-----------------------------------------------------------------------------
LISTE=""

# Theme GTK: Equinox +
LISTE=$LISTE" conky-all"
EQUINOX_ENGINE_VERSION="1.50"
EQUINOX_THEME_VERSION="1.50"
FAENZA_VERSION="0.9.2"

# Terminator
LISTE=$LISTE" terminator"
# Chromium Web Browser
LISTE=$LISTE" chromium-browser chromium-browser-l10n flashplugin-nonfree"
# Hotot
LISTE=$LISTE" hotot"
# Spotify
LISTE=$LISTE" spotify-client-qt spotify-client-gnome-support"
# Dropbox (pre-requis)
LISTE=$LISTE" libnautilus-extension-dev libnotify-dev python-docutils"
DROPBOX_VERSION="0.6.7"
# Multimedia: Vlc + ffmpeg
LISTE=$LISTE" vlc ffmpeg"
# Shutter: Capture d'image
LISTE=$LISTE" shutter"
# Dev
LISTE=$LISTE" subversion git"

#=============================================================================

# Test que le script est lance en root
if [ $EUID -ne 0 ]; then
  echo "Le script doit être lancé en root: # su - -c $0" 1>&2
  exit 1
fi

HOME_PATH=`grep $USERNAME /etc/passwd | awk -F':' '{ print $6 }'`

# Ajout des repos
# Generated by: http://debgen.simplylinux.ch/
#--------------------------------------------
cp /etc/apt/sources.list /etc/apt/sources.list-BACKUP
wget -q -O /etc/apt/sources.list http://svn.nicolargo.com/debianpostinstall/trunk/sources.list-debian6desktop

# Erreur Dynamic MMap ran out of room
echo 'APT::Cache-Limit "12500000";' >> /etc/apt/apt.conf

# Installation des cles
#----------------------

# Debian multimedia
apt-get update && apt-get install debian-multimedia-keyring && apt-get update
# Dotdeb
wget -q -O - http://www.dotdeb.org/dotdeb.gpg | apt-key add -
# Google
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# Skype
gpg --keyserver pgp.mit.edu --recv-keys 0xd66b746e && gpg --export --armor 0xd66b746e | apt-key add -
# Virtualbox
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | apt-key add -
# Hotot
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4E9CFF4E
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 07DC563D1F41B907

# Mise a jour des depots
#-----------------------

apt-get update
apt-get upgrade

# Installation des logiciels
#---------------------------

echo "Installation des logiciels suivants: $LISTE"
apt-get install $LISTE

# GStreamer "la totale"
#GSTREAMER_LISTE=`apt-cache search gstreamer | awk '{ print $1}' | xargs -eol`
#LISTE=$LISTE" $GSTREAMER_LISTE"
#apt-get install $GSTREAMER_LISTE

# Compile Dropbox depuis les sources
wget -O nautilus-dropbox-$DROPBOX_VERSION.tar.bz2 http://www.dropbox.com/download?dl=packages/nautilus-dropbox-$DROPBOX_VERSION.tar.bz2
bzip2 -d nautilus-dropbox-$DROPBOX_VERSION.tar.bz2
tar xvf nautilus-dropbox-$DROPBOX_VERSION.tar
cd nautilus-dropbox-$DROPBOX_VERSION
./configure
make
make install
cd -
rm -rf nautilus-dropbox-$DROPBOX_VERSION nautilus-dropbox-$DROPBOX_VERSION.tar

# Custom du systeme
#------------------

# GTK Theme
wget http://gnome-look.org/CONTENT/content-files/121881-equinox-$EQUINOX_ENGINE_VERSION.tar.gz
tar zxvf 121881-equinox-$EQUINOX_ENGINE_VERSION.tar.gz
cd equinox-$EQUINOX_ENGINE_VERSION
./configure --prefix=/usr --enable-animation
make install
rm -rf 121881-equinox-$EQUINOX_ENGINE_VERSION.tar.gz equinox-$EQUINOX_ENGINE_VERSION
wget http://gnome-look.org/CONTENT/content-files/140449-equinox-themes-$EQUINOX_THEME_VERSION.tar.gz
tar zxvf 140449-equinox-themes-$EQUINOX_THEME_VERSION.tar.gz
cp -R Equinox* /usr/share/themes/
rm -rf 140449-equinox-themes-$EQUINOX_THEME_VERSION.tar.gz
wget http://faenza-icon-theme.googlecode.com/files/faenza-icon-theme_$FAENZA_VERSION.tar.gz
tar zxvf faenza-icon-theme_$FAENZA_VERSION.tar.gz
cp -R Faenza* /usr/share/icons/
rm -rf faenza-icon-theme_$FAENZA_VERSION.tar.gz Faenza* AUTHORS COPYING ChangeLog README

# Conky
# Theme LUA 2011 - http://gnome-look.org/content/show.php?content=141411
wget http://gnome-look.org/CONTENT/content-files/141411-Conky-lua%202011%20next%20generation.tar.gz
tar zxvf "141411-Conky-lua 2011 next generation.tar.gz"
mkdir $HOME_PATH/.lua
mkdir $HOME_PATH/.lua/scripts
mkdir $HOME_PATH/.conky
cp "Conky-lua 2011 next generation/Debian/logo.png" $HOME_PATH/.conky
cp "Conky-lua 2011 next generation/Debian/clock_rings.lua" $HOME_PATH/.lua/scripts
cp "Conky-lua 2011 next generation/Debian/conkyrc" $HOME_PATH/.conkyrc
rm -rf "141411-Conky-lua 2011 next generation.tar.gz" "Conky-lua 2011 next generation"

# Custom .bashrc
cat >> $HOME_PATH/.bash_aliases << EOF
alias ll='ls -lF'
export MOZ_DISABLE_PANGO=1
EOF
source $HOME_PATH/.bashrc

# The end...
############

echo "##############################################################################"
echo ""
echo "                            Fin de l'installation"
echo ""
echo " 1) Automatiser lancement > sh -c \"sleep 20; /usr/bin/conky\" <";
echo "    dans Système > Préférences > Application au démarrage"
echo " 2) Redémarrer la machine"
echo " 3) Installer Dropbox sur votre session: Applications > Internet > Dropbox"
echo " 4) Selectionner le thème GTL: Système > Préférence > Apparence"
echo "       - Thème > Equinox Evolution Dawn"
echo "       - Personnaliser > Icônes > Faenza-Darkest"
echo ""
echo "##############################################################################"

